<a href="https://colab.research.google.com/github/ruthmanik/Tugas-Algoritma/blob/main/2208541028_RUTH%20SANI%20MANIK_TUGAS_V.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 5.16 List 2 Dimensi
List 2 dimennsi adalah menempatkan sebuah list du dalam list. penggambaran seperti matrik.

In [ ]:
#Tugas Pertemuan Senin, 3 April 2023

#Latihan List 2 Dimensi 1
#pertama kita akan membuat matrik
matrik = [
    [1,2,4,6],
    [8,10,12,14],
    [16,18,20,22],
    [24,26,28,30]
]
print(matrik)

[[1, 2, 4, 6], [8, 10, 12, 14], [16, 18, 20, 22], [24, 26, 28, 30]]


In [ ]:
#kita akan mengambil matrik "1"
matrik[1]

[8, 10, 12, 14]

In [ ]:
#kita akan coba mengambil matrik "1" "2"
matrik[1][2]

12

In [ ]:
#kita akan mencoba matrik "3" "3"
matrik[3][3]

30

In [ ]:
#dari data diatas kita bisa juga mengganti nilai matrik "3" "3" menjadi 60
matrik[3][3]= 60
print(matrik[3][3])

60


In [ ]:
#kita print lagi matrik
matrik
#maka akan tergantikan nilai dari matrik "3" "3" menjadi 60

[[1, 2, 4, 6], [8, 10, 12, 14], [16, 18, 20, 22], [24, 26, 28, 60]]

In [ ]:
#disini kita akan membuat matrik baris menjadi matrik kolom 
for baris in matrik:
    print(baris)
    for kolom in baris:
         print(kolom)

[1, 2, 4, 6]
1
2
4
6
[8, 10, 12, 14]
8
10
12
14
[16, 18, 20, 22]
16
18
20
22
[24, 26, 28, 60]
24
26
28
60


In [ ]:
#Latihan List 2 Dimensi 2

#pertama List minuman dengan 2 dimensi
list_minuman = [
    ["Teh", "Kopi", "Susu"],
    ["Jus Sirsak", "Jus Semangka", "Jus Jeruk"],
    ["Es Kopi", "Es Campur", "Es Teler"]
]

# Cara mengakses list 2 dimensi
# misalkan kita ingin mengambil "es kopi"
print(list_minuman[2][0])

Es Kopi


In [ ]:
#datanya masih sama seperti diatas
#pertama List minuman dengan 2 dimensi
list_minuman = [
    ["Teh", "Kopi", "Susu"],
    ["Jus Sirsak", "Jus Semangka", "Jus Jeruk"],
    ["Es Kopi", "Es Campur", "Es Teler"]
]

#kita ingin menampilkan semua isi dalam list
for menu in list_minuman:
    for minuman in menu:
        print(minuman)

Teh
Kopi
Susu
Jus Sirsak
Jus Semangka
Jus Jeruk
Es Kopi
Es Campur
Es Teler


# 5.17 Tuples 
Tuples dalam Python adalah stuktur data yang digunakan untuk menyimpan sekumpulan data. Mirip dengan list hanya tetapi tuples tidak dapat dirubah dan dihapus isinya

In [ ]:
#Latihan Tuples 1

#pertama kita list terlebih dahulu datanya
angka = (0,0,1,2,2,3,4,5)
#lalu kita print angka "1" maka ouput nya adalah 0 
print(angka[1])

0


In [ ]:
#lalu kita akan print "0:4" 
print(angka[0:4])

(0, 0, 1, 2)


In [ ]:
#dari data diatas kita akan buat dari baris menjadi kolom
for isi in angka [0:4]:
    print(isi)

0
0
1
2


In [ ]:
#kita akan mengubah angka "0" menjadi "10"
angka[0] = 10
#akan eror karena dari penjelasan diatas bahwa tuples tidak dapat diubah

TypeError: ignored

In [ ]:
#jika kita eksekusi akan eror karena tuples tidak dapat dirubah 
angka.append(10)

AttributeError: ignored

In [ ]:
#sama seperti diatas bahwa tidak dapat dirubah
angka.remove(5)

AttributeError: ignored

In [ ]:
#fungsi count() ini akan mengembalikan jumlah total elemen yang diberikan dalam sebuah string
angka.count(2)

2

In [ ]:
#fungsi index() digunakan untuk mengetahui posisi elemen pada list pemograman python
angka.index(3)

5

In [ ]:
#Latihan Tuples 2

#Kita dapat menggunakan tuples untuk menukar nilai yang terkait dengan variabel, hanya jika variabelnya adalah elemen tupel
x = 15
y = 51
print("sebelum ditukar:")
print(f"x = {x}, y = {y}")
(x, y) = (y, x)
print("sesudah ditukar:")
print(f"x = {x}, y = {y}")
#maka ouputnya akan menukar nilai dari x menjadi y dan y menjadi x

sebelum ditukar:
x = 15, y = 51
sesudah ditukar:
x = 51, y = 15


In [ ]:
#Latihan Tuples 3

#disini kita mengambil jumlah item didalam tuples 
#kita bisa menggunakan fungsi len()
# Membuat data
hari = ("Senin", "Selasa", "Rabu", "Kamis", "Jumat", "Sabtu", "Minggu")

# Mengambil jumlah item hari
print("Jumlah hari: %d" % len(hari))

Jumlah hari: 7


In [ ]:
#Latihan Tuples 4

#pertama kita list terlebih dahulu yang ingin kita list, misalkan
nama_buah = ("Sirsak" , "Melon" , "Semangka" , "Klengkeng")
#lalu kita print
print(nama_buah[0:1])
print(nama_buah[0:2])
print(nama_buah[1:3])
print(nama_buah[0:-1])
print(nama_buah[-1:-3])
print(nama_buah[-1:3])
print(nama_buah[-3:-1])
#tuples ini dilakukan menggunakan batas sebelah kanan mau pun sebelah kiri

('Sirsak',)
('Sirsak', 'Melon')
('Melon', 'Semangka')
('Sirsak', 'Melon', 'Semangka')
()
()
('Melon', 'Semangka')


In [ ]:
#kita list lagi seperti diatas 
nama_buah = ("Sirsak" , "Melon" , "Semangka" , "Klengkeng")
#lalu kita print, tetapi disini kita print tanpa harus mendefinisikan batas sebelah kanan maupun sebelah kiri
print(nama_buah[0:])
print(nama_buah[1:])
print(nama_buah[2:])
print(nama_buah[3:])
print(nama_buah[:0])
print(nama_buah[:1])
print(nama_buah[:2])
print(nama_buah[:3])
print(nama_buah[:4])


('Sirsak', 'Melon', 'Semangka', 'Klengkeng')
('Melon', 'Semangka', 'Klengkeng')
('Semangka', 'Klengkeng')
('Klengkeng',)
()
('Sirsak',)
('Sirsak', 'Melon')
('Sirsak', 'Melon', 'Semangka')
('Sirsak', 'Melon', 'Semangka', 'Klengkeng')


# 5.18 Dictionaries
Dictionaries digunakan jika data nya terkait satu sama lain. Misalnya data
seseorang yang terdiri dari umur, nama, tanggal lahir merupakan satu kesatuan
data yang bersumber dari orang tersebut.

In [ ]:
# Latihan Dictionaries 1

#pertama kita buat terlebih dahulu data orang
#data dibawah ini adalah data yang berkaitan 
data_orang = {
    "nama" : "Sultan" ,
    "umur": 23,
    "apakah_singel" : False
}

In [ ]:
#lalu kita akan print "nama"
print(data_orang["nama"])

Sultan


In [ ]:
#jika kita eksekusi akan eror karena pada "data orang"mengunakan "nama" bakan "Nama"
print(data_orang["Nama"])

KeyError: ignored

In [ ]:
#kita akan print data orang menggunakan get,dimana get untuk mendapatkan nilai kunci elemen dari data bertipe dictionaries
print(data_orang.get("nama"))

Sultan


In [ ]:
#jika di eksekusi akan menghasilkan "None" karena data orang menggunakan "nama" bukan "Nama"
#mengapa tidak eror karena kita menggunakan get, dimana get berfungsi untuk mendapatkan nilai kunci elemen dari data bertipe dictionaries
print(data_orang.get("Nama"))

None


In [ ]:
#jika di eksekusi akan menghasilkan "None" karena data orang diatas tidak membuat "tanggal lahir" jadi tidak dapat ditelusuri
#mengapa tidak eror karena kita menggunakan get, dimana get berfungsi untuk mendapatkan nilai kunci elemen dari data bertipe dictionaries
print(data_orang.get("tanggal_lahir"))

None


In [ ]:
#disini kita akan menambahkan "tanggal lahir"
print(data_orang.get("tanggal_lahir" , "12-4-2000"))

12-4-2000


In [ ]:
#lalu kita print data orang tersebut
print(data_orang)

{'nama': 'Sultan', 'umur': 23, 'apakah_singel': False}


In [ ]:
#jika kita eksekusi akan eror karena pada data orang yang sudah dibuat tidak membuat "tanggal lahir" jadi tidak dapat ditelusuri
print(data_orang["tanggal_lahir"])

KeyError: ignored

In [ ]:
#Larihan Dictionaries 2

pertemuan_hari_ini = {
  "judul": "Belajar Dictionaries 2 Pada Python ",
  "tanggal": "3 April 2023",
  "share_count": {
    "instagram": 1,
    "twitter": 2
  }
}
#kita akan print judul
print("Judul:", pertemuan_hari_ini.get("judul"))
#dan kita akan print tanggal
print("Tanggal:", pertemuan_hari_ini["tanggal"])

# bisa menggunakan fungsi berantai untuk dictionary bertingkat
print("Instagram share:", pertemuan_hari_ini.get("share_count").get("instagram"))
# bisa juga dengan kurung siku dua-duanya
print("Twitter share:", pertemuan_hari_ini["share_count"]["twitter"])

Judul: Belajar Dictionaries 2 Pada Python 
Tanggal: 3 April 2023
Instagram share: 1
Twitter share: 2


In [ ]:
#Latihan Dictionaries 3

#disini kita akan menggunakan perulangan 
mahasiswa = {
    "nama" : "Ruth" ,
    "nim"  : "2208541028"
}
#jika dijalankan kita akan mendapatkan
for key in mahasiswa:
  print(key, "->" , mahasiswa[key])

nama -> Ruth
nim -> 2208541028


In [ ]:
#disini kita akan menggunakan mengubah nilai item
#kita coba menggunakan data seperti yang diatas
mahasiswa = {
    "nama" : "Ruth" 
  }
#maka akan mengubah datanya
print("Nama awal:", mahasiswa.get("nama"))
mahasiswa["nama"] = "Ari"
print("Setelah diubah:", mahasiswa.get("nama"))
#Jika dieksekusi, sistem akan memberikan kita output

Nama awal: Ruth
Setelah diubah: Ari


In [ ]:
#disini kita akan menggunakan menambahkan nilai item
#kita coba menggunakan data seperti yang diatas
mahasiswa = {
    "nama" : "Ruth" 
  }
#output None nya
print("Hobi:", mahasiswa.get("hobi"))
#kita tambah datanya
mahasiswa["hobi"] = "Berenang"
#kita print ulang
print("Hobi dari {} adalah {}".format(
  mahasiswa.get('nama'),
  mahasiswa.get('hobi')
))
#Jika dieksekusi, sistem akan memberikan kita output

Hobi: None
Hobi dari Ruth adalah Berenang


In [ ]:
#disini kita akan menggunakan menghapus nilai item
#kita coba menggunakan data seperti yang diatas
mahasiswa = {
    "nama" : "Ruth",
    "nim"  :"2208541028"
 }
#maka akan menghapus datanya
del mahasiswa["nama"]
mahasiswa.pop("nim")
#Jika dieksekusi, sistem akan memberikan kita output

'2208541028'

# 5.19 Fungsi dalam Python
Fungsi pada python merupakan bagian atau blok program yang memiliki tugas tertentu. Fungsi pada python dapat digunakan berulang atau re-usable, kita hanya cukup sekali mendefinisikan fungsi dan ditempat lain pun bisa menggunakannya selama dalam satu program.

In [ ]:
#Latihan Fungsi dalam Python 1

#disini kita akan menginput nama depan dan nama belakang
def full_nama(first_name,last_name):
  print(f"Nama lengkapnya adalah {nama_depan} {nama_belakang}")
  
first_name = input("Nama depan saya adalah ")
last_name = input("Nama belakang saya adalah ")
full_nama = input("nama_depan,nama_belakang ")



Nama depan saya adalah Ruth
Nama belakang saya adalah Manik
nama_depan,nama_belakang Ruth Manik


In [24]:
#Latihan Fungsi dalam Python 2

#disini kita akan menginput berasal dan lahir
kota = "Medan"

def halo() :
  print(kota)

print("saya berasal dari ", kota)
print("dan saya lahir di ", end= " ")

halo()

saya berasal dari  Medan
dan saya lahir di  Medan


# 5.19.1 Tugas Fungsi pada Python
Ada dua jenis tugas fungsi pada Python yaitu:
menjalankan perintah, menampilkan hasil perhitungan.

In [17]:
#Latihan Tugas Fungsi pada Python 1

#disini kita akan membuat luas dari persegi
def luas_persegi(sisi):
    luas = sisi * sisi
    return luas

#lalu kita print fungsinya
print("Luas persegi: %d" % luas_persegi(5))

Luas persegi: 25


In [6]:
#disini kita akan membuat luas dari segitiga
def luas_segitiga(alas, tinggi):
    luas = (alas * tinggi) / 2
    print("Luas segitiga: %f" % luas)

#lalu kita print fungsinya
luas_segitiga(2, 3)

Luas segitiga: 3.000000


In [8]:
#disini kita akan membuat volume dari kubus
def volume_kubus(sisi):
  volume = sisi **3
  print('Volume Kubus adalah %0.2f' %volume)

#lalu kita print fusinya
volume_kubus(10)

Volume Kubus adalah 1000.00


In [14]:
 #Latihan Tugas Fungsi pada Python 2
 
 #jika return dieksekusi pada sebuah fungsi, maka semua proses yang ada di dalam blok kode fungsi tersebut akan berhenti
 #sehingga,jika kita memiliki lebih dari 1 buah return, maka hanya ada satu return saja yang dieksekusi
 #dan ketika sebuah return telah dieksekusi, semua perintah yang ada di bawahnya akan di-skip
 def persentase (total, jumlah):
  if (total >= 0 and total <= jumlah):
    return total / jumlah * 200
  
  return False

#output nya akan bernilai 100
print(persentase(20, 40))

#output nya akan bernilai False
print(persentase(200, 40))


100.0
False


# 5.20 Numpy
Numpy merupakan salah satu Library dalam Python yang memiliki keunggulan
dalam perhitungan menggunakan vektor,matrik, aljabar, statistik, dan sebagainya

# 5.20.1 Perintah Dasar pada Numpy
paparan mengenai perintah memanggil Numpy, mengetahui dimensi dan ukuran variabel 

In [8]:
#Latihan Perintah Dasar pada Numpy 1

# membuat array
a = np.array([85, 55, 40, 90])
# mengakses data pada array
print(a)

[85 55 40 90]


In [9]:
# membuat array
b = np.array([22,44,55,66])
# mengakses data pada array
print(b)

[22 44 55 66]


In [10]:
# membuat array
c = np.array([[[0,0,0,0],[1,1,1,1]],
              [[2,2,2,2],[3,3,3,3]],
              [[4,4,4,4],[5,5,5,5]]])
# mengakses data pada array
print(c)

[[[0 0 0 0]
  [1 1 1 1]]

 [[2 2 2 2]
  [3 3 3 3]]

 [[4 4 4 4]
  [5 5 5 5]]]


In [11]:
a.ndim

1

In [12]:
b.ndim

1

In [13]:
c.ndim

3

In [14]:
a.shape

(4,)

In [15]:
b.shape

(4,)

In [16]:
c.shape

(3, 2, 4)

In [20]:
#Latihan Perintah Dasar pada Numpy 2

#kita akan membuat bilangan A
Bil_A = np.array([1,2,3,4,5])
#lalu kita print yang ingin kita print
print(Bil_A[0])
print(Bil_A[2])
print(Bil_A[4])
print(Bil_A[0:4])
print(Bil_A[1:1])
print(Bil_A)

1
3
5
[1 2 3 4]
[]
[1 2 3 4 5]


# 5.20.2 Memanggil Anggota, Kolom dan Baris dengan Numpy
Program memanggil anggota, kolom dan baris dalam list menggunakan Numpy

In [6]:
#Latihan Memanggil Anggota, Kolom dan Baris dengan Numpy 1

# membuat array
d = np.array([[0,0,0,0],[1,1,1,1],[2,2,2,2],[3,3,3,3]])
# mengakses data pada array
print(d)

[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]]


In [26]:
d[3,3]

3

In [28]:
d[2,:]

array([2, 2, 2, 2])

In [29]:
d[:,1]

array([0, 1, 2, 3])

In [30]:
d[0,1:2]

array([0])

In [31]:
d[0,0:2:1]

array([0, 0])

In [33]:
d[1,1] = 33
print(d)

[[ 0  0  0  0]
 [ 1 33  1  1]
 [ 2  2  2  2]
 [ 3  3  3  3]]


In [14]:
#Latihan Memanggil Anggota, Kolom dan Baris dengan Numpy 2

#berikut cara melakukan slicing pada Array 2 dimensi
x = np.arange(10)
#lalu kita print
print(x)
print(x[2:8])
print(x[:5])
print(x[5:])
print(x[::2])
print(x[1::2])
print(x[1:7:2])
print(x[::-1])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7]
[0 1 2 3 4]
[5 6 7 8 9]
[0 2 4 6 8]
[1 3 5 7 9]
[1 3 5]
[9 8 7 6 5 4 3 2 1 0]


# 5.20.3 Matrix pada Numpy
Numpy dapat digunakan untuk membuat berbagai jenis matrix

In [16]:
#Latihan Matrix pada Numpy 1

#ones yang berfungsi untuk membuat array dengan semua elemen bernilai 1
np.ones((1,3))

array([[1., 1., 1.]])

In [17]:
#zeros yang berfungsi untuk mengubah semua elemen array menjadi 0 semua tanpa terkecuali
np.zeros((3,1))

array([[0.],
       [0.],
       [0.]])

In [18]:
#identity adalah jenis matrik yang semua elemen pada diagonal utamanya adalah satu (1) dan semua elemen lainnya adalah nol (0)
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
#ones berfungsi untuk membuat array dengan semua elemen bernilai 1 
np.ones((2,4,6))

array([[[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]])

In [20]:
#Fungsi full digunakan untuk mengisi array yang sudah ada dengan nilai yang sama
np.full((3,1),6)

array([[6],
       [6],
       [6]])

In [21]:
#fungsi random digunakan untuk menghasilkan angka acak di Python. Tidak benar-benar acak, melainkan ini digunakan untuk menghasilkan angka pseudo-acak
np.random.rand(5,2)

array([[0.65041541, 0.80331668],
       [0.44477933, 0.56904557],
       [0.0448696 , 0.36897483],
       [0.18612192, 0.58146605],
       [0.22229011, 0.84878211]])

In [22]:
#random.randint akan menghasilkan sebuah angka dengan tipe data integer acak dari parameter yang diberikan
#Fungsi ini membutuhkan 2 parameter yaitu angka minimum dan angka maksimum, dan python akan memberikan sebuah angka diantara 2 angka tersebut
np.random.randint(0,8,size=(4,4))

array([[4, 5, 4, 5],
       [6, 0, 1, 7],
       [5, 1, 0, 7],
       [1, 3, 3, 3]])

# 5.20.4 Copy pada Numpy
Copy memiliki data dan perubahan, apapun yang dilakukan pada copy tidak akan memengaruhi array asli, dan perubahan apa pun yang dibuat pada array asli tidak akan memengaruhi copy


In [4]:
#Latihan Copy pada Numpy 1

# membuat array
a = np.array([0,1,2,3,4])
# mengakses data pada array
print(a)


[0 1 2 3 4]


In [6]:
#kita akan membuat nilai a = nilai b
b = a
print(b)


[0 1 2 3 4]


In [14]:
#kita akan mengubah data 0 menjadi 5
b[0] = 5
print(b)

[5 1 2 3 4]


In [8]:
#lalu kita print nilai a dari data yang sudah kita ganti
print(a)

[5 1 2 3 4]


In [15]:
# membuat array
c = np.array([0,1,2,3,4])
# mengakses data pada array
print(c)

[0 1 2 3 4]


In [16]:
#lalu kita print d menggunakan copy
d = c.copy()
print(d)

[0 1 2 3 4]


In [12]:
#lalu kita ganti nilai 0 menjadi 5
d[0] = 5
print(d)

[5 1 2 3 4]


In [17]:
#lalu kita print c
print(c)

[0 1 2 3 4]


In [21]:
#Latihan Copy pada Numpy 2
#kita akan print menggunakan copy
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 10

print(arr)
print(x)

[10  2  3  4  5]
[1 2 3 4 5]


# 5.20.5 Operasi Matematika pada Numpy
Ada beberapa operasi dalam matematika

In [9]:
#Latihan Operasi Matematika pada Numpy 1

#operasi aritmatika
Bilangan_1 = np.array([1,2,3,4,5])
Bilangan_2 = np.array([1,1,1,1,1])

print("penjumlahan = ", Bilangan_1 + Bilangan_2)
print("pengurangan = ", Bilangan_1 - Bilangan_2)
print("perkalian = ", Bilangan_1 * Bilangan_2)
print("pembagian = ", Bilangan_1 / Bilangan_2)
print("perpangkatan = ", Bilangan_1 ** Bilangan_2)

penjumlahan =  [2 3 4 5 6]
pengurangan =  [0 1 2 3 4]
perkalian =  [1 2 3 4 5]
pembagian =  [1. 2. 3. 4. 5.]
perpangkatan =  [1 2 3 4 5]


# 5.20.6 Perkalian Matrik pada Numpy
 Konsep Perkalian Matriks adalah mengalikan elemen – elemen baris pada matriks pertama dengan elemen – elemen kolom pada matriks ke dua

In [5]:
#Latihan Perkalian Matrik pada Numpy 1

#perkalian matrik
matrik_A = np.array([[1,2],
                     [2,1]])
matrik_B = np.array([[2,2],
                     [1,1]])   
#kita kalikan matrik_A dengan matrik_B
perkalian_biasa = matrik_A*matrik_B
perkalian_matrik_1 = np.dot(matrik_A,matrik_B)
perkalian_matrik_2 = matrik_A.dot(matrik_B)

print("Matrik A :")
print(matrik_A)

print("Matrik B :")
print(matrik_B)

print("Perkalian Biasa Matrik : ")
print(perkalian_biasa)

print("Perkalian Matrik Cara 1 : ")
print(perkalian_matrik_1)

print("Perkalian Matrik Cara 2 : ")
print(perkalian_matrik_2)


Matrik A :
[[1 2]
 [2 1]]
Matrik B :
[[2 2]
 [1 1]]
Perkalian Biasa Matrik : 
[[2 4]
 [2 1]]
Perkalian Matrik Cara 1 : 
[[4 4]
 [5 5]]
Perkalian Matrik Cara 2 : 
[[4 4]
 [5 5]]


# 5.20.7 min, max dan sum pada Numpy
minimum, maksimum, dan penjumlahan

In [16]:
#Latihan min, max dan sum pada Numpy 1

#nilai minimum,maksimum, dan penjumlahan
matrik = np.array([1,2,3,4,5])
print("Nilai minimum = ", matrik.min())
print("Nilai maksimum = ", matrik.max())
print("Nilai penjumlahan = ", matrik.sum())

Nilai minimum =  1
Nilai maksimum =  5
Nilai penjumlahan =  15


In [15]:
#Latihan min, max dan sum pada Numpy 2
a = [3, 20, 100, -35, 50]

#nilai minimum,maksimum, dan penjumlahan
print(a)
print("Nilai maksimum:", max(a))
print("Nilai minimum:", min(a))
print("Nilai penjumlahan:", sum(a))

[3, 20, 100, -35, 50]
Nilai maksimum: 100
Nilai minimum: -35
Nilai penjumlahan: 138
